openapi: 3.2.0
info:
  title: Automile Resource Owner Route Planner API
  version: v1
tags:
- name: ResourceOwnerRoutePlanner
paths:
  /v1/resourceowner/routeplanner/routes:
    get:
      tags:
      - ResourceOwnerRoutePlanner
      summary: Get routes associated with the user
      description: 'Only routes that is either shared with the user or owned by the calling user is returned.


        Location Status enum values:


        *NotStarted = 0*


        *Done = 1*


        *Cancelled = 3*


        MissionStatus enum values:


        *Not Started = 0 (All route locations NotStarted)*


        *Ongoing = 1 (Any route location Done OR route mission started)*


        *Done = 2 (All route locations Done)*


        *Cancelled = 3 (Route mission Cancelled)*'
      operationId: ResourceOwnerRoutePlanner_GetRouteMissionsByDriverId
      responses:
        '200':
          description: The routes associated with the user is returned.
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoutePlannerMissionModel'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoutePlannerMissionModel'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoutePlannerMissionModel'
      security:
      - oauth2: []
  /v1/resourceowner/routeplanner/route/shorturlid/{shortUrlId}:
    get:
      tags:
      - ResourceOwnerRoutePlanner
      operationId: ResourceOwnerRoutePlanner_GetMissionByShortUrlId
      parameters:
      - in: path
        name: shortUrlId
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/RoutePlannerMissionModel'
            application/json:
              schema:
                $ref: '#/components/schemas/RoutePlannerMissionModel'
            text/json:
              schema:
                $ref: '#/components/schemas/RoutePlannerMissionModel'
      security:
      - oauth2: []
      summary: Resource owner route planner get mission by short url id
      x-summary-source: derived
  /v1/resourceowner/routeplanner/route/{routeId}:
    get:
      tags:
      - ResourceOwnerRoutePlanner
      operationId: ResourceOwnerRoutePlanner_GetMissionByRouteAndDriverId
      parameters:
      - in: path
        name: routeId
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/RoutePlannerMissionModel'
            application/json:
              schema:
                $ref: '#/components/schemas/RoutePlannerMissionModel'
            text/json:
              schema:
                $ref: '#/components/schemas/RoutePlannerMissionModel'
      security:
      - oauth2: []
      summary: Resource owner route planner get mission by route and driver id
      x-summary-source: derived
    put:
      tags:
      - ResourceOwnerRoutePlanner
      summary: Update a route state
      description: Only tasks that belongs to the user has access to will be returned.
      operationId: ResourceOwnerRoutePlanner_UpdateMission
      parameters:
      - in: path
        name: routeId
        description: The routeId to update
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: The stop was updated
        '500':
          description: Internal server error
        '403':
          description: Not authorized to task
      security:
      - oauth2: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UpdateStopModel'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UpdateStopModel'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UpdateStopModel'
        description: The stop location update model
  /v1/resourceowner/routeplanner/routes/routeandsave:
    post:
      tags:
      - ResourceOwnerRoutePlanner
      operationId: ResourceOwnerRoutePlanner_routeandsave
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema: {}
            application/json:
              schema: {}
            text/json:
              schema: {}
      security:
      - oauth2: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RouteRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/RouteRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/RouteRequest'
      summary: Resource owner route planner routeandsave
      x-summary-source: derived
  /v1/resourceowner/routeplanner/route/{routeId}/cancel:
    put:
      tags:
      - ResourceOwnerRoutePlanner
      summary: Set Route Status to Cancelled
      description: If a cancelled trip later gets 'uncancelled' the cancelling notes will be cleared
      operationId: ResourceOwnerRoutePlanner_CancelMission
      parameters:
      - in: path
        name: routeId
        description: The routeId to update
        required: true
        schema:
          type: integer
          format: int32
      - in: query
        name: notes
        description: Reason for cancelling
        schema:
          type: string
      responses:
        '200':
          description: Success
        '500':
          description: Internal server error
        '403':
          description: Not authorized to task
      security:
      - oauth2: []
  /v1/resourceowner/routeplanner/route/{routeId}/start:
    put:
      tags:
      - ResourceOwnerRoutePlanner
      summary: Set Route Status to Started
      operationId: ResourceOwnerRoutePlanner_StartMission
      parameters:
      - in: path
        name: routeId
        description: The routeId to update
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: Success
        '500':
          description: Internal server error
        '403':
          description: Not authorized to task
      security:
      - oauth2: []
  /v1/resourceowner/routeplanner:
    get:
      tags:
      - ResourceOwnerRoutePlanner
      summary: Get routes associated with the user
      description: '*OBSOLETE* Only routes that is either shared with the user or owned by the calling user is returned.'
      operationId: ResourceOwnerRoutePlanner_GetRouteMissions
      responses:
        '200':
          description: The routes associated with the user is returned.
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoutePlannerMissionModel'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoutePlannerMissionModel'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoutePlannerMissionModel'
      security:
      - oauth2: []
  /v1/resourceowner/routeplanner/{routeId}:
    get:
      tags:
      - ResourceOwnerRoutePlanner
      summary: Resource owner route planner get route mission
      description: '*OBSOLETE*'
      operationId: ResourceOwnerRoutePlanner_GetRouteMission
      parameters:
      - in: path
        name: routeId
        description: ''
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/RoutePlannerMissionModel'
            application/json:
              schema:
                $ref: '#/components/schemas/RoutePlannerMissionModel'
            text/json:
              schema:
                $ref: '#/components/schemas/RoutePlannerMissionModel'
      security:
      - oauth2: []
      x-summary-source: derived
components:
  schemas:
    RouteRequest:
      type: object
      properties:
        RouteName:
          type: string
        TimeConstraint:
          format: int32
          enum:
          - 0
          - 1
          type: integer
        When:
          format: date-time
          type: string
        UtcOffset:
          format: int64
          type: integer
        UserUnitType:
          format: int32
          enum:
          - 0
          - 1
          - 2
          type: integer
        FullAddresses:
          type: array
          items:
            type: string
        Strategy:
          format: int32
          enum:
          - 0
          - 1
          type: integer
        AvoidTollRoads:
          type: boolean
        AvoidHighways:
          type: boolean
        AvoidFerries:
          type: boolean
      additionalProperties: false
    RoutePlannerMissionModel:
      type: object
      properties:
        DistanceInKilometers:
          format: double
          type: number
        DurationInSeconds:
          format: double
          type: number
        RouteId:
          format: int32
          type: integer
        Name:
          type: string
        ContactId:
          format: int32
          type: integer
        IsDeparture:
          type: boolean
        OccuredAt:
          format: date-time
          type: string
        MissionStatus:
          format: int32
          enum:
          - 0
          - 1
          - 2
          - 3
          type: integer
        RouteStartedAtUTC:
          format: date-time
          type: string
        RouteStartedByContactId:
          format: int32
          type: integer
        RouteEndedAtUTC:
          format: date-time
          type: string
        Notes:
          type: string
        CreatedUTC:
          format: date-time
          type: string
        Locations:
          type: array
          items:
            $ref: '#/components/schemas/RoutePlannerMissionLocationModel'
      additionalProperties: false
    RoutePlannerMissionLocationModel:
      type: object
      properties:
        DistanceInKilometers:
          format: double
          type: number
        DurationInSeconds:
          format: double
          type: number
        Address:
          type: string
        Note:
          type: string
        RouteStopId:
          format: int32
          type: integer
        Status:
          format: int32
          enum:
          - 0
          - 1
          - 3
          type: integer
        DriverNotes:
          type: string
        Latitude:
          format: double
          type: number
        Longitude:
          format: double
          type: number
      additionalProperties: false
    UpdateStopModel:
      type: object
      properties:
        RouteStopId:
          format: int32
          type: integer
        Status:
          format: int32
          enum:
          - 0
          - 1
          - 3
          type: integer
        DriverNotes:
          type: string
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          scopes:
            read: Read access to protected resources
            write: Write access to protected resources
          authorizationUrl: https://api.automile.com/login/
      description: OAuth2 Implicit Grant
