openapi: 3.2.0
info:
  title: Automile Resource Owner Hours Of Service Violations API
  version: v1
tags:
- name: ResourceOwnerHoursOfServiceViolations
paths:
  /v1/resourceowner/hoursofserviceviolations:
    get:
      tags:
      - ResourceOwnerHoursOfServiceViolations
      summary: Get the Hours of Service Violations
      operationId: HoursOfServiceGetViolations
      parameters:
      - in: query
        name: fromDate
        description: Query on from date
        schema:
          type: string
          format: date-time
      - in: query
        name: toDate
        description: Query on to date
        schema:
          type: string
          format: date-time
      - in: query
        name: hourOfServiceViolationId
        description: Query on to id
        schema:
          type: integer
          format: int32
      - in: query
        name: contactId
        description: Get statuses for a contact
        schema:
          type: integer
          format: int32
      - in: query
        name: vehicleId
        description: Get statuses for a vehicle
        schema:
          type: integer
          format: int32
      - in: query
        name: notes
        description: Query on notes
        schema:
          type: string
      responses:
        '200':
          description: The settings is returned, null if no settings exist
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HoursOfServiceDutyStatusModel'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HoursOfServiceDutyStatusModel'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HoursOfServiceDutyStatusModel'
      security:
      - oauth2: []
    post:
      tags:
      - ResourceOwnerHoursOfServiceViolations
      summary: Creates Hours Of Service Violation
      operationId: HoursOfSerivceCreateViolation
      responses:
        '200':
          description: A link in the header is returned to the newly resource
      security:
      - oauth2: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HoursOfServiceViolationCreateModel'
          text/json:
            schema:
              $ref: '#/components/schemas/HoursOfServiceViolationCreateModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/HoursOfServiceViolationCreateModel'
        description: The settings model
components:
  schemas:
    HoursOfServiceViolationCreateModel:
      type: object
      properties:
        HoursOfServiceLogId:
          format: int32
          type: integer
        ViolationType:
          format: int32
          type: integer
        RequiredActionType:
          format: int32
          type: integer
        StartDateTime:
          format: date-time
          description: UTC
          type: string
        EndDateTime:
          format: date-time
          description: UTC
          type: string
      additionalProperties: false
    HoursOfServiceDutyStatusModel:
      type: object
      properties:
        HoursOfServiceLogId:
          format: int32
          type: integer
        VehicleId:
          format: int32
          type: integer
        DutyStatusType:
          format: int32
          enum:
          - 0
          - 1
          - 2
          - 3
          type: integer
        FromDateTime:
          format: date-time
          description: From date UTC
          type: string
        ToDateTime:
          format: date-time
          description: To date UTC
          type: string
        Notes:
          type: string
        Location:
          type: string
        CycleRuleType:
          format: int32
          enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          type: integer
        WorkDayStartTime:
          $ref: '#/components/schemas/TimeSpan'
        DistanceInKm:
          format: double
          type: number
        CreatedDateTime:
          format: date-time
          description: Created UTC
          type: string
        ModifiedDateTime:
          format: date-time
          description: Modified UTC
          type: string
        ExternalId:
          format: uuid
          type: string
        IsDeleted:
          type: boolean
      additionalProperties: false
    TimeSpan:
      type: object
      properties:
        Ticks:
          format: int64
          type: integer
        Days:
          format: int32
          type: integer
          readOnly: true
        Hours:
          format: int32
          type: integer
          readOnly: true
        Milliseconds:
          format: int32
          type: integer
          readOnly: true
        Microseconds:
          format: int32
          type: integer
          readOnly: true
        Nanoseconds:
          format: int32
          type: integer
          readOnly: true
        Minutes:
          format: int32
          type: integer
          readOnly: true
        Seconds:
          format: int32
          type: integer
          readOnly: true
        TotalDays:
          format: double
          type: number
          readOnly: true
        TotalHours:
          format: double
          type: number
          readOnly: true
        TotalMilliseconds:
          format: double
          type: number
          readOnly: true
        TotalMicroseconds:
          format: double
          type: number
          readOnly: true
        TotalNanoseconds:
          format: double
          type: number
          readOnly: true
        TotalMinutes:
          format: double
          type: number
          readOnly: true
        TotalSeconds:
          format: double
          type: number
          readOnly: true
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          scopes:
            read: Read access to protected resources
            write: Write access to protected resources
          authorizationUrl: https://api.automile.com/login/
      description: OAuth2 Implicit Grant
