openapi: 3.2.0
info:
  title: Automile Resource Owner Content API
  version: v1
tags:
- name: ResourceOwnerContent
paths:
  /v1/resourceowner/content/upload:
    post:
      tags:
      - ResourceOwnerContent
      summary: Upload binary file
      description: Upload attachment image and returns url
      operationId: ResourceOwnerContentController_Upload
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ContentUploadResponseModel'
            application/json:
              schema:
                $ref: '#/components/schemas/ContentUploadResponseModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ContentUploadResponseModel'
        '400':
          description: Missing or invalid data
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '406':
          description: Request is not properly formatted
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal server error
        '201':
          description: Successfully uploaded
      security:
      - oauth2: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                ContentType:
                  type: string
                ContentDisposition:
                  type: string
                Headers:
                  type: string
                Length:
                  type: integer
                  format: int64
                Name:
                  type: string
                FileName:
                  type: string
  /v1/resourceowner/content/download/{guid}:
    get:
      tags:
      - ResourceOwnerContent
      summary: Get a binary file content
      operationId: ResourceOwnerContentController_Get
      parameters:
      - in: path
        name: guid
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The binary file is returned
      security:
      - oauth2: []
components:
  schemas:
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          format: int32
          type: integer
        detail:
          type: string
        instance:
          type: string
      additionalProperties: {}
    ContentUploadResponseModel:
      type: object
      properties:
        URL:
          type: string
        GUID:
          format: uuid
          type: string
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          scopes:
            read: Read access to protected resources
            write: Write access to protected resources
          authorizationUrl: https://api.automile.com/login/
      description: OAuth2 Implicit Grant
