openapi: 3.2.0
info:
  title: Automile Resource Owner User API
  version: v1
tags:
- name: ResourceOwnerUser
paths:
  /v1/resourceowner/user:
    get:
      tags:
      - ResourceOwnerUser
      summary: This get's the details of the current user that you are logged in as
      description: This will return the details of the current user.
      operationId: GetResourceOwnerUser
      responses:
        '200':
          description: The User is returned
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/UserModel'
            application/json:
              schema:
                $ref: '#/components/schemas/UserModel'
            text/json:
              schema:
                $ref: '#/components/schemas/UserModel'
        '500':
          description: Internal server error
      security:
      - oauth2: []
  /v1/resourceowner/user/changepassword:
    put:
      tags:
      - ResourceOwnerUser
      summary: Change the password of the current user that you are logged in as
      description: This will change the password.
      operationId: ChangePasswordResourceOwnerUser
      responses:
        '200':
          description: The password was saved
        '400':
          description: Request is bad, the password is too short or doesn't contains at least one uppercase character, one lowercase character, one number and one complex characte that you tried to update doesn't exist
        '403':
          description: Request is forbidden, meaning that the password entered is invalid
        '500':
          description: Internal server error
      security:
      - oauth2: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordModel'
          text/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ChangePasswordModel'
        description: The change password model
  /v1/resourceowner/user/userexistingpassword:
    get:
      tags:
      - ResourceOwnerUser
      summary: Check if the user has a password set
      description: This will get info if user has existing password.
      operationId: UserExistingPassword
      responses:
        '200':
          description: The info is returned
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/UserExistingPasswordModel'
            application/json:
              schema:
                $ref: '#/components/schemas/UserExistingPasswordModel'
            text/json:
              schema:
                $ref: '#/components/schemas/UserExistingPasswordModel'
        '500':
          description: Internal server error
      security:
      - oauth2: []
  /v1/resourceowner/user/changeusername:
    put:
      tags:
      - ResourceOwnerUser
      summary: Change the username of the current user that you are logged in as
      description: This will change the username.
      operationId: ChangeUserNameResourceOwnerUser
      responses:
        '200':
          description: The username was saved
        '400':
          description: Request is bad, This username is already used
        '500':
          description: Internal server error
      security:
      - oauth2: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeUserNameModel'
          text/json:
            schema:
              $ref: '#/components/schemas/ChangeUserNameModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ChangeUserNameModel'
        description: The change  username model
  /v1/resourceowner/user/resetpassword:
    post:
      tags:
      - ResourceOwnerUser
      summary: Reset the password by SMS for the current user logged in
      operationId: ResetPasswordResourceOwnerUser
      responses:
        '200':
          description: A reset password sms was sent
        '400':
          description: Request is bad, password reset type does not exist
        '404':
          description: Phone number is missing
        '500':
          description: Internal server error
      security:
      - oauth2: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordUserModel'
          text/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordUserModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ResetPasswordUserModel'
        description: The reset password model
  /v1/resourceowner/user/logout:
    post:
      tags:
      - ResourceOwnerUser
      summary: Logs out the user
      description: Logs out the user and the users client device id will be removed from the users available client devices. A new user client device id will be created on login.
      operationId: ResourceOwnerUserController_Logout
      responses:
        '200':
          description: Successful log out
        '403':
          description: No access to the client device
        '500':
          description: Internal server error
      security:
      - oauth2: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutModel'
          text/json:
            schema:
              $ref: '#/components/schemas/LogoutModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/LogoutModel'
        description: Model containing the users client device id
components:
  schemas:
    ChangePasswordModel:
      type: object
      properties:
        CurrentPassword:
          type: string
        NewPassword:
          type: string
      additionalProperties: false
    UserModel:
      type: object
      properties:
        UserId:
          format: int32
          type: integer
        UserGuid:
          format: uuid
          type: string
        UserName:
          type: string
        ContactId:
          format: int32
          type: integer
      additionalProperties: false
    ResetPasswordUserModel:
      type: object
      properties:
        Email:
          type: string
        ResetPasswordType:
          format: int32
          enum:
          - 0
          - 1
          type: integer
      additionalProperties: false
    ChangeUserNameModel:
      type: object
      properties:
        NewUserName:
          type: string
      additionalProperties: false
    UserExistingPasswordModel:
      type: object
      properties:
        HasPassword:
          type: boolean
      additionalProperties: false
    LogoutModel:
      required:
      - UserDeviceId
      type: object
      properties:
        UserDeviceId:
          format: int32
          type: integer
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          scopes:
            read: Read access to protected resources
            write: Write access to protected resources
          authorizationUrl: https://api.automile.com/login/
      description: OAuth2 Implicit Grant
