openapi: 3.2.0
info:
  title: Automile Client API Authorizations API
  version: v1
tags:
- name: ClientApiAuthorizations
paths:
  /v1/client/apiauthorizations:
    get:
      tags:
      - ClientApiAuthorizations
      summary: Get a list of user that has authorized the logged in API client for access
      description: Only users that has given authorization to the given API client will be returned
      responses:
        '200':
          description: The users are returned
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/APIAuthorizationModel'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/APIAuthorizationModel'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/APIAuthorizationModel'
        '500':
          description: Internal server error
      security:
      - oauth2: []
      operationId: getV1ClientApiauthorizations
      x-operation-id-source: derived
  /v1/client/apiauthorizations/{apiAuthorizationId}:
    get:
      tags:
      - ClientApiAuthorizations
      summary: Get the details about a specific user authorization
      operationId: GetByAPIAuthorizationId
      parameters:
      - in: path
        name: apiAuthorizationId
        description: The id of the authorization
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: The user details are returned
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/APIAuthorizationModel'
            application/json:
              schema:
                $ref: '#/components/schemas/APIAuthorizationModel'
            text/json:
              schema:
                $ref: '#/components/schemas/APIAuthorizationModel'
        '403':
          description: Request is forbidden, meaning you dont' have access to this authorization
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal server error
      security:
      - oauth2: []
components:
  schemas:
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          format: int32
          type: integer
        detail:
          type: string
        instance:
          type: string
      additionalProperties: {}
    APIAuthorizationModel:
      type: object
      properties:
        APIAuthorizationId:
          format: int32
          type: integer
        IssueDate:
          format: date-time
          type: string
        APIClientId:
          format: int32
          type: integer
        UserId:
          format: int32
          type: integer
        ScopesDelimitedBySpaces:
          type: string
        ExpirationDateUtc:
          format: date-time
          type: string
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          scopes:
            read: Read access to protected resources
            write: Write access to protected resources
          authorizationUrl: https://api.automile.com/login/
      description: OAuth2 Implicit Grant
