openapi: 3.2.0
info:
  title: Automile Resource Owner Contact Setting API
  version: v1
tags:
- name: ResourceOwnerContactSetting
paths:
  /v1/resourceowner/contactsetting/{contactId}:
    get:
      tags:
      - ResourceOwnerContactSetting
      summary: Get a list of all settings available for a contact
      operationId: contactsetting_GetSettingList
      parameters:
      - in: path
        name: contactId
        description: The contact id
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: The contacts are returned
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContactSettingModelGET'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContactSettingModelGET'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContactSettingModelGET'
        '500':
          description: Internal server error
      security:
      - oauth2: []
    put:
      tags:
      - ResourceOwnerContactSetting
      summary: Edit a setting for the user
      operationId: contactsetting_EditSetting
      parameters:
      - in: path
        name: contactId
        description: The contact id
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: The setting was saved
        '500':
          description: Internal server error
        '403':
          description: Request is forbidden, this could occur if you are not associated with the contact
      security:
      - oauth2: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactSettingModelPUT'
          text/json:
            schema:
              $ref: '#/components/schemas/ContactSettingModelPUT'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ContactSettingModelPUT'
        description: The setting to edit and its new value (null = remove)
  /v1/resourceowner/contactsetting/settingkeylist:
    get:
      tags:
      - ResourceOwnerContactSetting
      summary: Get a list of all settings available to set on a contact
      operationId: contactsetting_GetSettingKeyList
      responses:
        '200':
          description: The contacts are returned
          content:
            text/plain:
              schema:
                type: array
                items:
                  type: string
            application/json:
              schema:
                type: array
                items:
                  type: string
            text/json:
              schema:
                type: array
                items:
                  type: string
        '500':
          description: Internal server error
      security:
      - oauth2: []
components:
  schemas:
    ContactSettingModelPUT:
      type: object
      properties:
        Name:
          type: string
        Value:
          type: string
      additionalProperties: false
    ContactSettingModelGET:
      type: object
      properties:
        Name:
          type: string
        Value:
          type: string
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          scopes:
            read: Read access to protected resources
            write: Write access to protected resources
          authorizationUrl: https://api.automile.com/login/
      description: OAuth2 Implicit Grant
