openapi: 3.2.0
info:
  title: Automile Client Custom API
  version: v1
tags:
- name: ClientCustom
paths:
  /v1/client/custom/createuser:
    post:
      tags:
      - ClientCustom
      summary: Creates Client Custom User
      operationId: CreateClientCustomUser
      responses:
        '200':
          description: Client Custom user created
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CreatedAtRoute'
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedAtRoute'
            text/json:
              schema:
                $ref: '#/components/schemas/CreatedAtRoute'
        '500':
          description: Internal server error
      security:
      - oauth2: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomUserCreateModel'
          text/json:
            schema:
              $ref: '#/components/schemas/CustomUserCreateModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CustomUserCreateModel'
        description: The custom user model
  /v1/client/custom/resetpassword:
    post:
      tags:
      - ClientCustom
      summary: Reset User password
      operationId: ResetPasswordClientCustom
      responses:
        '200':
          description: Password reset sent
        '500':
          description: Internal server error
      security:
      - oauth2: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordUserModel'
          text/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordUserModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ResetPasswordUserModel'
        description: The reset password model
  /v1/client/custom/createuserwithoutpassword:
    post:
      tags:
      - ClientCustom
      summary: Create User without password
      operationId: CreateClientCustomUserWithoutPassword
      responses:
        '200':
          description: Create User without password
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/UserCreatedPasswordModel'
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreatedPasswordModel'
            text/json:
              schema:
                $ref: '#/components/schemas/UserCreatedPasswordModel'
        '500':
          description: Internal server error
      security:
      - oauth2: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomUserCreateWithoutPasswordModel'
          text/json:
            schema:
              $ref: '#/components/schemas/CustomUserCreateWithoutPasswordModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CustomUserCreateWithoutPasswordModel'
        description: The reset password model
  /v1/client/custom/usernametaken:
    get:
      tags:
      - ClientCustom
      summary: Get UserName takenmodel
      operationId: UsernameTaken
      parameters:
      - in: query
        name: username
        description: The username
        schema:
          type: string
      responses:
        '200':
          description: The UserNametaken returned
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/UsernameTakenModel'
            application/json:
              schema:
                $ref: '#/components/schemas/UsernameTakenModel'
            text/json:
              schema:
                $ref: '#/components/schemas/UsernameTakenModel'
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/UsernameTakenModel'
            application/json:
              schema:
                $ref: '#/components/schemas/UsernameTakenModel'
            text/json:
              schema:
                $ref: '#/components/schemas/UsernameTakenModel'
      security:
      - oauth2: []
  /v1/client/custom/userphonenumber:
    get:
      tags:
      - ClientCustom
      summary: Get User assoicated to phonenumber or username
      operationId: UserPhoneNumber
      parameters:
      - in: query
        name: identifier
        description: username or phonenumber
        schema:
          type: string
      - in: query
        name: region
        description: Region for phonenumber
        schema:
          type: string
      responses:
        '200':
          description: The user returned
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserPhoneNumberModel'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserPhoneNumberModel'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserPhoneNumberModel'
        '400':
          description: Bad request, can happen when you supply values that are unacceptable
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '409':
          description: Multiple users assoicated to the account
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal server error
      security:
      - oauth2: []
  /v1/client/custom/usersphonenumber:
    get:
      tags:
      - ClientCustom
      summary: Get user guids from phonenumber
      operationId: UsernamesPhoneNumber
      parameters:
      - in: query
        name: mobilePhoneNumber
        description: ''
        schema:
          type: string
      - in: query
        name: region
        description: Region for phonenumber
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UsernamesPhoneNumberModel'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UsernamesPhoneNumberModel'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UsernamesPhoneNumberModel'
      security:
      - oauth2: []
  /v1/client/custom/existingusers:
    get:
      tags:
      - ClientCustom
      summary: Get user guids from identifier
      operationId: ExistingUsersAccounts
      parameters:
      - in: query
        name: identifier
        description: ''
        schema:
          type: string
      - in: query
        name: region
        description: Region for phonenumber
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UsernamesPhoneNumberModel'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UsernamesPhoneNumberModel'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UsernamesPhoneNumberModel'
      security:
      - oauth2: []
  /v1/client/custom/validatephonenumber:
    get:
      tags:
      - ClientCustom
      summary: Check if user has the phonenumber
      operationId: ValidatePhoneNumber
      parameters:
      - in: query
        name: username
        description: ''
        schema:
          type: string
      - in: query
        name: mobilePhoneNumber
        description: ''
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: boolean
            application/json:
              schema:
                type: boolean
            text/json:
              schema:
                type: boolean
      security:
      - oauth2: []
  /v1/client/custom/deviceregistered:
    get:
      tags:
      - ClientCustom
      summary: Get DeviceRegistered
      operationId: DeviceRegistered
      parameters:
      - in: query
        name: imei
        description: The Imei
        schema:
          type: string
      responses:
        '200':
          description: The DeviceRegistered returned
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/DeviceRegisteredModel'
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceRegisteredModel'
            text/json:
              schema:
                $ref: '#/components/schemas/DeviceRegisteredModel'
        '500':
          description: Internal server error
      security:
      - oauth2: []
  /v1/client/custom/reversegeocoding:
    get:
      tags:
      - ClientCustom
      summary: Get DeviceRegistered
      operationId: ReverseGeocoding
      parameters:
      - in: query
        name: latitude
        description: The latitude
        schema:
          type: number
          format: double
      - in: query
        name: longitude
        description: The longitude
        schema:
          type: number
          format: double
      responses:
        '200':
          description: The DeviceRegistered returned
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ReverseGeocodingResult'
            application/json:
              schema:
                $ref: '#/components/schemas/ReverseGeocodingResult'
            text/json:
              schema:
                $ref: '#/components/schemas/ReverseGeocodingResult'
        '500':
          description: Internal server error
      security:
      - oauth2: []
components:
  schemas:
    ResetPasswordUserModel:
      type: object
      properties:
        Email:
          type: string
        ResetPasswordType:
          format: int32
          enum:
          - 0
          - 1
          type: integer
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          format: int32
          type: integer
        detail:
          type: string
        instance:
          type: string
      additionalProperties: {}
    UserCreatedPasswordModel:
      type: object
      properties:
        Password:
          type: string
      additionalProperties: false
    CustomUserCreateWithoutPasswordModel:
      required:
      - EmailAddress
      - UserName
      type: object
      properties:
        UserName:
          minLength: 1
          type: string
        FirstName:
          type: string
        LastName:
          type: string
        EmailAddress:
          format: email
          minLength: 1
          type: string
        MobilePhoneNumber:
          type: string
        Description:
          type: string
        Culture:
          type: string
        IMEI:
          type: string
        SerialNumber:
          type: string
        UnitType:
          format: int32
          enum:
          - 0
          - 1
          - 2
          type: integer
      additionalProperties: false
    DeviceRegisteredModel:
      type: object
      properties:
        QueriedDeviceIMEI:
          type: string
        IsRegistered:
          type: boolean
      additionalProperties: false
    CreatedAtRoute:
      type: object
      properties:
        RouteName:
          type: string
          readOnly: true
        RouteValues:
          type: object
          additionalProperties: {}
          readOnly: true
        StatusCode:
          format: int32
          type: integer
          readOnly: true
      additionalProperties: false
    ReverseGeocodingResult:
      type: object
      properties:
        FormattedAddress:
          type: string
      additionalProperties: false
    UserPhoneNumberModel:
      type: object
      properties:
        UserName:
          type: string
        PhoneNumber:
          type: string
        UserGuid:
          format: uuid
          type: string
        OrganizationId:
          format: int32
          type: integer
      additionalProperties: false
    CustomUserCreateModel:
      required:
      - EmailAddress
      - IMEI
      - SerialNumber
      - UserName
      type: object
      properties:
        UserName:
          minLength: 1
          type: string
        FirstName:
          type: string
        LastName:
          type: string
        EmailAddress:
          format: email
          minLength: 1
          type: string
        MobilePhoneNumber:
          type: string
        Description:
          type: string
        Password:
          type: string
        IMEI:
          minLength: 1
          type: string
        SerialNumber:
          minLength: 1
          type: string
        Culture:
          type: string
        UnitType:
          format: int32
          enum:
          - 0
          - 1
          - 2
          type: integer
      additionalProperties: false
    UsernameTakenModel:
      type: object
      properties:
        Username:
          type: string
        Taken:
          type: boolean
      additionalProperties: false
    SSOConfigurationModel:
      type: object
      properties:
        ClientId:
          type: string
        TenantId:
          type: string
        Scopes:
          type: array
          items:
            type: string
      additionalProperties: false
    UsernamesPhoneNumberModel:
      type: object
      properties:
        UserName:
          type: string
        UserGuid:
          format: uuid
          type: string
        MobilePhoneNumber:
          type: string
        SSO:
          type: boolean
        SSOConfig:
          $ref: '#/components/schemas/SSOConfigurationModel'
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          scopes:
            read: Read access to protected resources
            write: Write access to protected resources
          authorizationUrl: https://api.automile.com/login/
      description: OAuth2 Implicit Grant
