openapi: 3.2.0
info:
  title: Automile Resource Owner Trip Score API
  version: v1
tags:
- name: ResourceOwnerTripScore
paths:
  /v1/resourceowner/tripscore/drivingscore/{driverContactId}:
    get:
      tags:
      - ResourceOwnerTripScore
      summary: Get latest driving score for a driver
      description: 'This is a BETA feature, under development and may change.


        Reduction types are "HarshAcceleration", "HarshBrake", "HarshTurn", "Idling" or "Speeding".


        Returns latest driving score with points lost, weaknesses and strengths'
      operationId: GetResourceOwnerLatestDrivingScore
      parameters:
      - in: path
        name: driverContactId
        description: Contact id to get driving score for
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/DrivingScoreModel'
            application/json:
              schema:
                $ref: '#/components/schemas/DrivingScoreModel'
            text/json:
              schema:
                $ref: '#/components/schemas/DrivingScoreModel'
      security:
      - oauth2: []
  /v1/resourceowner/tripscore/summary/{driverContactId}:
    get:
      tags:
      - ResourceOwnerTripScore
      summary: Get trip score summary for a driver
      description: 'This is a BETA feature, under development and may change.


        Reduction types are "HarshAcceleration", "HarshBrake", "HarshTurn", "Idling" or "Speeding".


        Returns summary for previous month and current month.'
      operationId: GetResourceOwnerTripScoreSummary
      parameters:
      - in: path
        name: driverContactId
        description: Contact id to get trip score for
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TripScoreSummaryModel'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TripScoreSummaryModel'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TripScoreSummaryModel'
      security:
      - oauth2: []
  /v1/resourceowner/tripscore/chartdata/{driverContactId}:
    get:
      tags:
      - ResourceOwnerTripScore
      summary: Get trip score chart data for a driver
      description: This is a BETA feature, under development and may change.
      operationId: GetResourceOwnerTripScoreChartData
      parameters:
      - in: path
        name: driverContactId
        description: Contact id to get chart for
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/TripScoreChartDataListModel'
            application/json:
              schema:
                $ref: '#/components/schemas/TripScoreChartDataListModel'
            text/json:
              schema:
                $ref: '#/components/schemas/TripScoreChartDataListModel'
      security:
      - oauth2: []
  /v1/resourceowner/tripscore/triplist/{driverContactId}:
    get:
      tags:
      - ResourceOwnerTripScore
      summary: Get list of trips with trip score for a driver
      description: 'This is a BETA feature, under development and may change.


        Max return count is 100 trips.'
      operationId: GetResourceOwnerTripScoreTripList
      parameters:
      - in: path
        name: driverContactId
        description: Contact id to get trip score for
        required: true
        schema:
          type: integer
          format: int32
      - in: query
        name: skip
        description: Optional skip number of trips
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TripScoreTripModel'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TripScoreTripModel'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TripScoreTripModel'
      security:
      - oauth2: []
components:
  schemas:
    TripScoreReductionModel:
      type: object
      properties:
        Type:
          format: int32
          type: integer
        Value:
          format: double
          type: number
        Text:
          type: string
      additionalProperties: false
    TripScoreChartDataModel:
      type: object
      properties:
        AverageTripScore:
          format: int32
          type: integer
        DrivingScore:
          format: int32
          type: integer
        Date:
          type: string
      additionalProperties: false
    DrivingScoreModel:
      type: object
      properties:
        Date:
          format: date-time
          type: string
        DrivingScore:
          format: int32
          type: integer
        OrganizationScore:
          format: int32
          type: integer
        Reductions:
          type: array
          items:
            $ref: '#/components/schemas/TripScoreReductionModel'
        Strengths:
          type: array
          items:
            $ref: '#/components/schemas/TripScoreReductionModel'
      additionalProperties: false
    TripScoreChartDataListModel:
      type: object
      properties:
        ContactChartDataList:
          type: array
          items:
            $ref: '#/components/schemas/TripScoreChartDataModel'
        OrganizationChartDataList:
          type: array
          items:
            $ref: '#/components/schemas/TripScoreChartDataModel'
          readOnly: true
      additionalProperties: false
    TripScoreTripModel:
      type: object
      properties:
        AuthorizedToViewTrip:
          type: boolean
        TripId:
          format: int32
          type: integer
        TripEndAddress:
          type: string
        TripEndDateTime:
          format: date-time
          type: string
        TripScore:
          format: int32
          type: integer
        TripStartAddress:
          type: string
        TripStartDateTime:
          format: date-time
          type: string
      additionalProperties: false
    TripScoreSummaryModel:
      type: object
      properties:
        AverageTripScore:
          format: int32
          type: integer
        FromDate:
          type: string
        Reductions:
          type: array
          items:
            $ref: '#/components/schemas/TripScoreReductionModel'
        Strengths:
          type: array
          items:
            $ref: '#/components/schemas/TripScoreReductionModel'
        ToDate:
          type: string
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          scopes:
            read: Read access to protected resources
            write: Write access to protected resources
          authorizationUrl: https://api.automile.com/login/
      description: OAuth2 Implicit Grant
