openapi: 3.2.0
info:
  title: Automile Resource Owner Trigger Messages API
  version: v1
tags:
- name: ResourceOwnerTriggerMessages
paths:
  /v1/resourceowner/triggermessageshistory:
    get:
      tags:
      - ResourceOwnerTriggerMessages
      summary: Get all trigger messages that the logged in user has access to
      description: Only trigger messages that belongs to vehicles that the user has access to will be returned.
      operationId: GetResourceOwnerTriggerMessagesHistory
      responses:
        '200':
          description: The trigger messages are returned
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TriggerMessageHistoryModel'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TriggerMessageHistoryModel'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TriggerMessageHistoryModel'
        '500':
          description: Internal server error
      security:
      - oauth2: []
  /v1/resourceowner/triggermessageshistory/{triggerId}:
    get:
      tags:
      - ResourceOwnerTriggerMessages
      summary: Get trigger messages by trigger id
      description: Only trigger messages that belongs to vehicles that the user has access to will be returned.
      operationId: GetResourceOwnerTriggerMessageHistory
      parameters:
      - in: path
        name: triggerId
        description: The Id of the company
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: The trigger messages are returned
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TriggerMessageHistoryModel'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TriggerMessageHistoryModel'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TriggerMessageHistoryModel'
        '404':
          description: The trigger message that you tried to get doesn't exist
        '500':
          description: Internal server error
      security:
      - oauth2: []
components:
  schemas:
    TriggerMessageHistoryModel:
      type: object
      properties:
        TriggerMessageHistoryId:
          format: int32
          type: integer
        TriggerId:
          format: int32
          type: integer
        WasSentOn:
          format: date-time
          type: string
        DestinationType:
          format: int32
          enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          type: integer
        DestinationData:
          type: string
        MessageData1:
          type: string
        MessageData2:
          type: string
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          scopes:
            read: Read access to protected resources
            write: Write access to protected resources
          authorizationUrl: https://api.automile.com/login/
      description: OAuth2 Implicit Grant
